import {
  Briefcase,
  BulbIcon,
  CarParking01FreeIcons,
  ChairBarberIcon,
  Dumbbell,
  EngineFreeIcons,
  Laundry,
  Leaf,
  MilkBottleFreeIcons,
  Snowflake,
  Tv,
  UtensilsCrossed,
  Waves,
  Wifi01FreeIcons,
  ZapIcon,
} from "@hugeicons/core-free-icons";
import { IconSvgElement } from "@hugeicons/react";

export const amenityIcons: Record<string, IconSvgElement> = {
  wifi: Wifi01FreeIcons,
  pool: Waves,
  gym: Dumbbell,
  restaurant: UtensilsCrossed,
  dining: UtensilsCrossed,
  spa: Leaf,
  business: Briefcase,
  bar: MilkBottleFreeIcons,
  parking: CarParking01FreeIcons,
  laundry: Laundry,
  ac: Snowflake,
  "Air conditioning": Snowflake,
  "USB charging": ZapIcon,
  "Wi-Fi": Wifi01FreeIcons,
  "Reading lights": BulbIcon,
  "Reclining seats": ChairBarberIcon,
  generator: EngineFreeIcons,
  tv: Tv,
};
